FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/apps/api/dist ./apps/api/dist
RUN apk add --no-cache ffmpeg
RUN mkdir -p /app/storage/uploads
EXPOSE 3333
CMD ["node","apps/api/dist/server.js"]
