import { describe,expect,it } from "vitest";
import fs from "node:fs/promises";
import path from "node:path";
import { config } from "./config.js";
import { MockAIProvider, OpenAICompatibleProvider, OpenAICompatibleTranscriptionProvider } from "./ai.js";
import { parseLocalWhisperDocument } from "./localWhisper.js";

describe("mock AI",()=>{
  it("extracts decisions, entities, and open loops",async()=>{const r=await new MockAIProvider().analyzeSource("I decided that Project Atlas will use PostgreSQL instead of SQLite. I still need to migrate the old records this weekend.","Atlas note");expect(r.memories.some(x=>x.type==="decision"&&/PostgreSQL/.test(x.content))).toBe(true);expect(r.openLoops[0].description).toMatch(/migrate/);expect(r.entities.some(x=>x.name.includes("Atlas"))).toBe(true);});
  it("answers with grounded context",async()=>{const r=await new MockAIProvider().answerQuestion("What database did I choose?","- I decided to use PostgreSQL for Atlas");expect(r).toMatch(/PostgreSQL/);});
  it("requests verbose JSON with segment timestamps",async()=>{const filePath=path.join(config.dataDir,"uploads","provider-payload-test.webm");await fs.writeFile(filePath,"audio");const originalFetch=globalThis.fetch;let requestBody:FormData|undefined;globalThis.fetch=async(_input,init)=>{requestBody=init?.body as FormData;return new Response(JSON.stringify({text:"Hello world",language:"en",segments:[{start:1.2,end:2.4,text:"Hello world"}],words:[{word:"Hello",start:1.2,end:1.7},{word:"world",start:1.8,end:2.4}]}),{status:200,headers:{"content-type":"application/json"}});};try{const result=await new OpenAICompatibleTranscriptionProvider({baseUrl:"https://api.groq.com/openai/v1",apiKey:"test-key",model:"whisper-large-v3"}).transcribe({filePath,sourceId:"provider-test",mimeType:"audio/webm"});expect(requestBody?.get("model")).toBe("whisper-large-v3");expect(requestBody?.get("response_format")).toBe("verbose_json");expect(requestBody?.getAll("timestamp_granularities[]")).toEqual(["segment"]);expect(result.segments[0].startMs).toBe(1200);expect(result.segments[0].words?.[1].endMs).toBe(2400);}finally{globalThis.fetch=originalFetch;await fs.rm(filePath,{force:true});}});
  it("parses whisper.cpp offsets as Noted transcript timestamps",()=>{const result=parseLocalWhisperDocument({result:{language:"en"},transcription:[{offsets:{from:1250,to:2600},text:" Local first. "},{offsets:{from:3000,to:4400},text:"Returned to Noted."}]},"Local first.\nReturned to Noted.");expect(result.language).toBe("en");expect(result.text).toBe("Local first.\nReturned to Noted.");expect(result.segments).toEqual([{startMs:1250,endMs:2600,text:"Local first."},{startMs:3000,endMs:4400,text:"Returned to Noted."}]);});
  it("requests strict Groq analysis and normalizes provider categories",async()=>{const originalFetch=globalThis.fetch;const original={llmMode:config.llmMode,llmBaseUrl:config.llmBaseUrl,llmApiKey:config.llmApiKey,llmModel:config.llmModel};let requestBody:any;config.llmMode="real";config.llmBaseUrl="https://api.groq.com/openai/v1";config.llmApiKey="test-key";config.llmModel="openai/gpt-oss-120b";globalThis.fetch=async(_input,init)=>{requestBody=JSON.parse(String(init?.body));return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({summary:"A useful note.",memories:[{type:"insight",content:"Keep the recording local.",importance:1.4,confidence:.9,evidence:[]}],entities:[{type:"concept",name:"Local capture"}],openLoops:[],relationships:[],meeting:{keyPoints:[],decisions:[],actionItems:[],suggestedFollowUps:[],unresolvedQuestions:[]}})}}]}),{status:200,headers:{"content-type":"application/json"}});};try{const result=await new OpenAICompatibleProvider().analyzeSource("Keep the recording local.","Capture note",[{segmentIndex:0,text:"Keep the recording local."}]);expect(requestBody.response_format.type).toBe("json_schema");expect(requestBody.response_format.json_schema.strict).toBe(true);expect(requestBody.model).toBe("openai/gpt-oss-120b");expect(result.memories[0].type).toBe("observation");expect(result.memories[0].importance).toBe(1);expect(result.entities[0].type).toBe("topic");expect(result.meeting.summary).toBe("A useful note.");}finally{globalThis.fetch=originalFetch;Object.assign(config,original);}});
  it("splits bounded local analysis and merges canonical evidence",async()=>{const originalFetch=globalThis.fetch;const original={llmMode:config.llmMode,llmBaseUrl:config.llmBaseUrl,llmApiKey:config.llmApiKey,llmModel:config.llmModel,llmAnalysisChunkChars:config.llmAnalysisChunkChars,llmAnalysisTimeoutMs:config.llmAnalysisTimeoutMs};const requestBodies:Record<string,unknown>[]=[];config.llmMode="real";config.llmBaseUrl="http://127.0.0.1:11434/v1";config.llmApiKey="ollama";config.llmModel="qwen3:8b";config.llmAnalysisChunkChars=12;config.llmAnalysisTimeoutMs=0;globalThis.fetch=async(_input,init)=>{const body:Record<string,unknown>=JSON.parse(String(init?.body));requestBodies.push(body);const index=requestBodies.length-1;const segmentIndex=index;const segmentText=index===0?"alpha beta":"gamma delta";const content={summary:`Window ${index+1}`,memories:[{type:"task",content:"Book follow-up",importance:.8,confidence:.8,evidence:[{segmentIndex,text:segmentText}]}],entities:[],openLoops:[],relationships:[],meeting:{keyPoints:[],decisions:[],actionItems:[{text:"Book follow-up",confidence:.8,evidence:[{segmentIndex,text:segmentText}]}],suggestedFollowUps:[],unresolvedQuestions:[]}};return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(content)}}]}),{status:200,headers:{"content-type":"application/json"}});};try{const result=await new OpenAICompatibleProvider().analyzeSource("alpha beta\ngamma delta","Visit",[{segmentIndex:0,text:"alpha beta"},{segmentIndex:1,text:"gamma delta"}]);expect(requestBodies).toHaveLength(2);expect(requestBodies.every((body)=>((body.response_format as {type?:string})?.type === "json_object"))).toBe(true);expect(result.summary).toContain("Window 1");expect(result.summary).toContain("Window 2");expect(result.meeting.actionItems).toHaveLength(1);expect(result.meeting.actionItems[0].evidence?.map((item)=>item.segmentIndex)).toEqual([0,1]);expect(result.meeting.actionItems[0].evidence?.map((item)=>item.text)).toEqual(["alpha beta","gamma delta"]);}finally{globalThis.fetch=originalFetch;Object.assign(config,original);}});
  it("normalizes compact local JSON and infers canonical evidence",async()=>{const originalFetch=globalThis.fetch;const original={llmMode:config.llmMode,llmBaseUrl:config.llmBaseUrl,llmApiKey:config.llmApiKey,llmModel:config.llmModel,llmAnalysisChunkChars:config.llmAnalysisChunkChars,llmAnalysisTimeoutMs:config.llmAnalysisTimeoutMs};config.llmMode="real";config.llmBaseUrl="http://127.0.0.1:11434/v1";config.llmApiKey="ollama";config.llmModel="qwen3:8b";config.llmAnalysisChunkChars=0;config.llmAnalysisTimeoutMs=0;globalThis.fetch=async()=>{const content={summary:"Alpha follow-up discussed.",memories:["Discuss alpha follow-up"],entities:["Follow-up"],openLoops:["Book alpha follow-up"],relationships:["Follow-up"],meeting:{keyPoints:["Alpha follow-up discussed"],decisions:[],actionItems:["Book alpha follow-up"],suggestedFollowUps:[],unresolvedQuestions:[]}};return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(content)}}]}),{status:200,headers:{"content-type":"application/json"}});};try{const result=await new OpenAICompatibleProvider().analyzeSource("alpha follow-up is needed.","Visit",[{segmentIndex:7,startMs:100,endMs:200,text:"alpha follow-up is needed."}]);expect(result.memories[0].content).toBe("Discuss alpha follow-up");expect(result.meeting.actionItems[0].evidence).toEqual([{segmentIndex:7,startMs:100,endMs:200,text:"alpha follow-up is needed."}]);}finally{globalThis.fetch=originalFetch;Object.assign(config,original);}});
});
