import fs from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { config } from "./config.js";
import type { EntityType, MemoryType, TranscriptWord } from "./types.js";

export interface EvidenceHint { segmentIndex:number; startMs?:number; endMs?:number; text:string; }
export interface Analysis { summary:string; memories:{type:MemoryType;content:string;importance:number;confidence:number;occurredAt?:string;evidence?:EvidenceHint[]}[]; entities:{type:EntityType;name:string;description?:string}[]; openLoops:{description:string;confidence:number;dueAt?:string;evidence?:EvidenceHint[]}[]; relationships:{entityName:string;relationshipType:string;confidence:number}[]; }
export interface AIProvider { analyzeSource(text:string,title:string,evidenceSegments?:EvidenceHint[]):Promise<Analysis>; answerQuestion(question:string,context:string):Promise<string>; }
export interface TranscriptionInput { filePath:string; mimeType?:string; sourceId:string; durationMs?:number; }
export interface TranscriptionSegment { startMs?:number; endMs?:number; text:string; speaker?:string; confidence?:number; words?:TranscriptWord[]; chunkIndex?:number; chunkStartMs?:number; }
export interface TranscriptionResult { text:string; segments:TranscriptionSegment[]; language?:string; }
export interface TranscriptionProvider { transcribe(input:TranscriptionInput):Promise<TranscriptionResult>; }
export interface TranscriptionProviderSettings { baseUrl:string; apiKey:string; model:string; }

const analysisSchema=z.object({summary:z.string().default(""),memories:z.array(z.object({type:z.string(),content:z.string(),importance:z.number().min(0).max(1).default(.5),confidence:z.number().min(0).max(1).default(.7),evidence:z.array(z.object({segmentIndex:z.number().int().nonnegative(),startMs:z.number().optional(),endMs:z.number().optional(),text:z.string().default("")})).optional()})).default([]),entities:z.array(z.object({type:z.string(),name:z.string(),description:z.string().optional()})).default([]),openLoops:z.array(z.object({description:z.string(),confidence:z.number().min(0).max(1).default(.7),dueAt:z.string().optional(),evidence:z.array(z.object({segmentIndex:z.number().int().nonnegative(),startMs:z.number().optional(),endMs:z.number().optional(),text:z.string().default("")})).optional()})).default([]),relationships:z.array(z.object({entityName:z.string(),relationshipType:z.string(),confidence:z.number().min(0).max(1).default(.7)})).default([])});
function sentenceParts(text:string){return text.replace(/\s+/g," ").split(/(?<=[.!?])\s+|\n+/).map(x=>x.trim()).filter(x=>x.length>8);}
function titleEntities(text:string){const found=new Set<string>();for(const m of text.matchAll(/\b(?:Project\s+)?[A-Z][A-Za-z0-9-]{2,}(?:\s+[A-Z][A-Za-z0-9-]{2,})?\b/g)){const n=m[0].replace(/^I\s+/i,"");if(!/^(The|This|That|What|When|Because|PostgreSQL|SQLite|OpenAI|Fusion|OCR|I|We)$/.test(n))found.add(n);}return [...found];}
const evidenceFor=(text:string,index:number,segments?:EvidenceHint[])=>{if(!segments?.length)return undefined;const lower=text.toLowerCase();return segments.filter(s=>lower.includes(s.text.toLowerCase().slice(0,Math.min(28,s.text.length)))||s.segmentIndex===index).slice(0,1);};

export class MockAIProvider implements AIProvider {
  async analyzeSource(text:string,title:string,evidenceSegments?:EvidenceHint[]):Promise<Analysis>{const sentences=sentenceParts(text);const memories:Analysis["memories"]=[];const loops:Analysis["openLoops"]=[];for(const [index,s] of sentences.entries()){const lower=s.toLowerCase();const isLoop=/\b(still need|need to|needs to|remind me|should |follow up|todo|unfinished|have to)\b/.test(lower);const evidence=evidenceFor(s,index,evidenceSegments);if(isLoop)loops.push({description:s.replace(/[.!?]$/,""),confidence:.91,evidence});let type:MemoryType="observation";if(/\b(decided|decision|choose|chose|changed my mind|will use|using|instead of)\b/.test(lower))type="decision";else if(/\b(idea|could |might |what if|consider)\b/.test(lower))type="idea";else if(/\?\s*$/.test(s))type="question";else if(/\b(prefer|like|always|avoid)\b/.test(lower))type="preference";else if(/\b(on |met |meeting|yesterday|today|tomorrow|said|told)\b/.test(lower))type="event";if(!isLoop||type!=="observation")memories.push({type,content:s,importance:type==="decision"?.9:isLoop?.8:.55,confidence:.86,evidence});}if(!memories.length&&text.trim())memories.push({type:"reference",content:text.trim().slice(0,500),importance:.5,confidence:.7,evidence:evidenceSegments?.slice(0,1)});const names=titleEntities(`${title} ${text}`);const entities=names.map(name=>({type:(/\b(postgresql|sqlite|react|typescript|ocr|docker|fusion)\b/i.test(name)?"technology":/^(Bill|Yancy|Alice|Bob)$/i.test(name)?"person":"project") as EntityType,name}));return {summary:(sentences[0]??text).slice(0,240),memories,entities,openLoops:loops,relationships:entities.map(e=>({entityName:e.name,relationshipType:"mentions",confidence:.8}))};}
  async answerQuestion(question:string,context:string){const lines=context.split("\n").filter(Boolean);const q=question.toLowerCase();if(!lines.length)return "I don't have enough evidence in your memories to answer that confidently.";if(/database|storage|sql|choose|decid/.test(q)){const preferred=lines.find(l=>/postgresql/i.test(l)&&!/superseded/i.test(l));if(preferred)return `You chose PostgreSQL for the project. ${preferred.replace(/^[-*]\s*/,"")}`;const any=lines.find(l=>/sqlite/i.test(l));if(any)return `The available memory mentions SQLite, but I could not confirm it is still current. ${any.replace(/^[-*]\s*/,"")}`;}const relevant=lines.find(l=>q.split(/\W+/).some(t=>t.length>3&&l.toLowerCase().includes(t)))??lines[0];return `Based on your captured memories: ${relevant.replace(/^[-*]\s*/,"")}`;}
}

export class FixtureTranscriptionProvider implements TranscriptionProvider { constructor(private readonly fixture:string|TranscriptionResult){} async transcribe(_input:TranscriptionInput){if(typeof this.fixture!=="string")return this.fixture;return {text:this.fixture,segments:[{text:this.fixture}]};} }

function milliseconds(value:unknown){return typeof value==="number"&&Number.isFinite(value)?Math.round(value*1000):undefined;}
function parseWord(raw:any):TranscriptWord|undefined{const word=String(raw?.word??raw?.text??"").trim();if(!word)return undefined;return {word,startMs:typeof raw?.startMs==="number"?raw.startMs:milliseconds(raw?.start),endMs:typeof raw?.endMs==="number"?raw.endMs:milliseconds(raw?.end),confidence:typeof raw?.confidence==="number"?raw.confidence:undefined};}
function parseSegment(raw:any):TranscriptionSegment|undefined{const text=String(raw?.text??"").trim();if(!text)return undefined;const words=Array.isArray(raw?.words)?raw.words.map(parseWord).filter(Boolean) as TranscriptWord[]:undefined;return {startMs:typeof raw?.startMs==="number"?raw.startMs:milliseconds(raw?.start),endMs:typeof raw?.endMs==="number"?raw.endMs:milliseconds(raw?.end),text,speaker:typeof raw?.speaker==="string"?raw.speaker:undefined,confidence:typeof raw?.confidence==="number"?raw.confidence:undefined,words};}
export function parseTranscriptionResponse(raw:unknown):TranscriptionResult {const value=raw&&typeof raw==="object"?raw as any:{};const text=typeof value.text==="string"?value.text.trim():"";const topWords=Array.isArray(value.words)?value.words.map(parseWord).filter(Boolean) as TranscriptWord[]:[];let segments=Array.isArray(value.segments)?value.segments.map(parseSegment).filter(Boolean) as TranscriptionSegment[]:[];if(topWords.length&&segments.length){segments=segments.map(segment=>{const start=segment.startMs??0;const end=segment.endMs??Number.MAX_SAFE_INTEGER;const words=topWords.filter(word=>{const point=word.startMs??word.endMs??0;return point>=start&&point<=end;});return {...segment,words:words.length?words:segment.words};});}else if(topWords.length&&!segments.length&&text){segments=[{text,startMs:topWords[0].startMs,endMs:topWords.at(-1)?.endMs,words:topWords}];}
  if(!text&&segments.length) return {text:segments.map(s=>s.text).join(" ").trim(),segments,language:typeof value.language==="string"?value.language:undefined};
  return {text,segments:text&&!segments.length?[{text}]:segments,language:typeof value.language==="string"?value.language:undefined};}

export class OpenAICompatibleTranscriptionProvider implements TranscriptionProvider {
  private readonly settings:TranscriptionProviderSettings;
  constructor(settings:TranscriptionProviderSettings={baseUrl:config.transcriptionBaseUrl,apiKey:config.transcriptionApiKey,model:config.transcriptionModel}){this.settings=settings;}
  async transcribe(input:TranscriptionInput):Promise<TranscriptionResult>{const body=new FormData();const bytes=await fs.readFile(input.filePath);body.append("file",new Blob([bytes],{type:input.mimeType??"application/octet-stream"}),path.basename(input.filePath));body.append("model",this.settings.model);body.append("response_format","verbose_json");body.append("timestamp_granularities[]","segment");body.append("timestamp_granularities[]","word");const response=await fetch(`${this.settings.baseUrl.replace(/\/$/,"")}/audio/transcriptions`,{method:"POST",headers:{Authorization:`Bearer ${this.settings.apiKey}`},body});if(!response.ok)throw new Error(`Transcription provider returned ${response.status}`);const result=parseTranscriptionResponse(await response.json());if(!result.text)throw new Error("Transcription provider returned no text");return result;}
}

export class OpenAICompatibleProvider implements AIProvider {private readonly fallback=new MockAIProvider();async analyzeSource(text:string,title:string,evidenceSegments?:EvidenceHint[]){if(!(config.llmBaseUrl&&config.llmApiKey&&config.llmMode==="real"))return this.fallback.analyzeSource(text,title,evidenceSegments);const response=await fetch(`${config.llmBaseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${config.llmApiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:config.llmModel,messages:[{role:"system",content:"Extract structured personal-memory data. Return only valid JSON matching summary, memories(type/content/importance/confidence/evidence), entities(type/name), openLoops(description/confidence/evidence), relationships."},{role:"user",content:`Title: ${title}\nEvidence segments: ${JSON.stringify(evidenceSegments??[])}\nText:\n${text}`}],response_format:{type:"json_object"},temperature:0.1})});if(!response.ok)throw new Error(`AI provider returned ${response.status}`);const json=await response.json() as any;const content=json.choices?.[0]?.message?.content;if(typeof content!=="string")throw new Error("AI provider returned no structured content");return analysisSchema.parse(JSON.parse(content)) as Analysis;}
  async answerQuestion(question:string,context:string){if(!(config.llmBaseUrl&&config.llmApiKey&&config.llmMode==="real"))return this.fallback.answerQuestion(question,context);const response=await fetch(`${config.llmBaseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${config.llmApiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:config.llmModel,messages:[{role:"system",content:"Answer only from the supplied personal-memory evidence. If it is insufficient, say so."},{role:"user",content:`Question: ${question}\nEvidence:\n${context}`}],temperature:0.1})});if(!response.ok)throw new Error(`AI provider returned ${response.status}`);const json=await response.json() as any;return String(json.choices?.[0]?.message?.content??"I don't have enough evidence in your memories to answer that confidently.");}}

export const aiProvider:AIProvider=config.llmMode==="real"?new OpenAICompatibleProvider():new MockAIProvider();
export const transcriptionProvider:TranscriptionProvider|undefined=config.transcriptionMode!=="disabled"&&config.transcriptionApiKey&&config.transcriptionBaseUrl&&config.transcriptionModel?new OpenAICompatibleTranscriptionProvider():undefined;
