import { aiProvider, transcriptionProvider } from "./ai.js";
import { store } from "./db.js";
import { chunkText } from "./chunking.js";
import { transcribeWithChunking } from "./transcription.js";
import type { EntityType, EvidenceRef, Source, TranscriptSegment } from "./types.js";

const active=new Set<string>();
const stopWords=new Set(["this","that","with","from","will","have","about","instead","into","said","still","need","what","were","they","than"]);
function evidenceRefs(sourceId:string,hints:({segmentIndex:number;startMs?:number;endMs?:number;text:string}|undefined)[]|undefined,segments:TranscriptSegment[]):EvidenceRef[]{const refs:EvidenceRef[]=[];for(const h of hints??[]){if(!h)continue;const segment=segments.find(s=>s.segmentIndex===h.segmentIndex);refs.push({sourceId,segmentId:segment?.id,startMs:h.startMs??segment?.startMs,endMs:h.endMs??segment?.endMs,quote:h.text||segment?.text});}return refs;}
function transcriptHints(source:Source):{segmentIndex:number;startMs?:number;endMs?:number;text:string}[]{return store.transcriptForSource(source.id).map(s=>({segmentIndex:s.segmentIndex,startMs:s.startMs,endMs:s.endMs,text:s.text}));}
function asTranscriptSegments(result:{text:string;segments:Array<{startMs?:number;endMs?:number;text:string;speaker?:string;confidence?:number;words?:TranscriptSegment["words"];chunkIndex?:number;chunkStartMs?:number}>}):Array<Omit<TranscriptSegment,"id"|"sourceId"|"createdAt">>{return result.segments.length?result.segments.map((s,segmentIndex)=>({...s,segmentIndex})): [{segmentIndex:0,text:result.text}];}

export async function processSource(sourceId:string,jobId?:string){if(active.has(sourceId))return;active.add(sourceId);const source=store.getSource(sourceId);if(!source){active.delete(sourceId);return;}try{if(jobId)store.updateJob(jobId,"processing");store.updateSource(sourceId,{processingStatus:"processing",processingError:undefined});let text=source.transcriptText||source.extractedText||source.originalText;let segments=store.transcriptForSource(sourceId);
    if(source.type==="voice"&&!text){if(!source.filePath||!transcriptionProvider){store.updateSource(sourceId,{processingStatus:"partial",transcriptStatus:"partial",processingError:"Audio is saved, but no transcription provider is configured. Add a transcript or configure one, then retry."});if(source.recordingSessionId)store.updateRecordingSession(source.recordingSessionId,{status:"partial"});if(jobId)store.updateJob(jobId,"complete");active.delete(sourceId);return;}store.updateSource(sourceId,{transcriptStatus:"processing"});const result=await transcribeWithChunking(transcriptionProvider,{filePath:source.filePath,mimeType:source.audioMimeType??source.mimeType,sourceId,durationMs:source.durationMs});const transcriptSegments=asTranscriptSegments(result);segments=store.replaceTranscript(sourceId,transcriptSegments);text=result.text;store.updateSource(sourceId,{transcriptText:text,extractedText:text,transcriptStatus:"ready"});}
    if(source.type==="url"&&!text){try{const r=await fetch(source.sourceUrl!,{signal:AbortSignal.timeout(6000)});if(!r.ok)throw new Error(`URL returned ${r.status}`);const html=await r.text();text=html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim().slice(0,20000);if(!text)throw new Error("No readable text found");store.updateSource(sourceId,{extractedText:text});}catch(e){const message=e instanceof Error?e.message:"URL content could not be fetched";store.updateSource(sourceId,{processingStatus:"partial",processingError:`URL saved, but content extraction failed: ${message}`});if(jobId)store.updateJob(jobId,"complete");active.delete(sourceId);return;}}
    if(!text){store.updateSource(sourceId,{processingStatus:"partial",processingError:"The source is saved, but no text is available for analysis yet."});if(jobId)store.updateJob(jobId,"complete");active.delete(sourceId);return;}
    if(source.type==="voice"&&!segments.length){segments=store.replaceTranscript(sourceId,[{segmentIndex:0,text}]);}if(source.type!=="voice")segments=[];const hints=source.type==="voice"?transcriptHints(source):undefined;store.clearDerived(sourceId);store.replaceChunks(sourceId,chunkText(text));const analysis=await aiProvider.analyzeSource(text,source.title,hints);const created=[];for(const m of analysis.memories){const refs=evidenceRefs(sourceId,m.evidence,segments);const memory=store.createMemory({id:crypto.randomUUID(),sourceId,memoryType:m.type,content:m.content,summary:m.content.slice(0,240),importance:m.importance,confidence:m.confidence,occurredAt:m.occurredAt,status:"active",metadata:{},evidenceRefs:refs});created.push(memory);}
    for(const e of analysis.entities){const entity=store.upsertEntity(e.type as EntityType,e.name,e.description??"");for(const memory of created)store.addRelationship({fromType:"memory",fromId:memory.id,relationshipType:"mentions",toType:"entity",toId:entity.id,confidence:.8,sourceId});}
    for(const loop of analysis.openLoops){const memory=created.find(m=>m.content===loop.description)||created.find(m=>m.memoryType==="task")||created[0];if(memory)store.addLoop({memoryId:memory.id,description:loop.description,status:"open",confidence:loop.confidence,dueAt:loop.dueAt,evidenceRefs:evidenceRefs(sourceId,loop.evidence,segments)});}
    const decisions=created.filter(m=>m.memoryType==="decision");if(decisions.length){const old=store.listMemories("decision").filter(m=>m.sourceId!==sourceId&&!m.supersededBy);for(const newer of decisions){for(const previous of old){const newerTokens=new Set(newer.content.toLowerCase().split(/\W+/).filter(t=>t.length>3&&!stopWords.has(t)));const overlap=previous.content.toLowerCase().split(/\W+/).some(t=>newerTokens.has(t));if(overlap&&new Date(previous.createdAt)<new Date(newer.createdAt))store.updateMemory(previous.id,{supersededBy:newer.id,metadata:{...previous.metadata,supersededReason:"Newer decision overlaps this source"}});}}}
    store.updateSource(sourceId,{processingStatus:"ready",processingError:undefined,summary:analysis.summary,transcriptStatus:source.type==="voice"?"ready":source.transcriptStatus});if(source.recordingSessionId)store.updateRecordingSession(source.recordingSessionId,{status:"ready"});if(jobId)store.updateJob(jobId,"complete");
  }catch(e){const message=e instanceof Error?e.message:"Processing failed";store.updateSource(sourceId,{processingStatus:"failed",processingError:message,transcriptStatus:source.type==="voice"?"failed":source.transcriptStatus});if(source.recordingSessionId)store.updateRecordingSession(source.recordingSessionId,{status:"failed"});if(jobId)store.updateJob(jobId,"failed",message);}finally{active.delete(sourceId);}}
export function queueSource(sourceId:string){const job=store.createJob(sourceId);void processSource(sourceId,job);return job;}
